### ISSUE TITLE
Cambio en el modelo de Locations

### ISSUE THREAD

**Issue by rpasquini** [fscorro/TangelaServices#3]
Es necesario que el modelo de la base contemple que hay locations que son sublocations (children) de otras locations. Es necesario porque un pedido al API de startups en una location determinada, por ejemplo, muchas veces  no incluye  las startups de sus children. Es decir, para rastrear todas las startups de una location dada es necesario buscar en sus sublocations
Propongo entonces que se implemente un modelo con un nuevo edge llamado HasChildrenLocation.
Location-->HasChildrenLocation-->Location
Creo que el modelo de locations como fue propuesto inicialmente, con superclasses para estados, países etc, requeriría que cada vez que se popule la data se vincule la startup a sus parent locations.  Con el modelo de HasChildrenLocation entiendo que esto se simplificaría. 
Ya que este modelo de obtener children locations es provisto por Angellist API, nuestro servicio debería apuntar a tomar una consulta al API de Angellist y generar  ambos verteces y edges.

**Comment by fscorro** [comment]
Hoy en día ya existe una relación entre Locations y es BelongTo. Creo que lo que se debería cambiar dentro del proceso es obtener los últimos hijos de la Location que se ingresa y hacer la busqueda de las startups sobre esas Locations. Lo importante es que la relación existe.
